#!/bin/zsh
distributionConfig=$(jq "
.CallerReference=\"`uuidgen`\"" \
  scripts/aws:cloudfront/distribution-config.json)
aws cloudfront create-distribution \
  --distribution-config file://<(echo $distributionConfig) | \
  jq .Distribution.Id -r | tr -d '\n' > scripts/aws:cloudfront/distribution-id
