#!/bin/zsh
distributionConfig=$(jq "
.Distribution.DistributionConfig|.CallerReference=\"`uuidgen`\"" \
  scripts/aws:cloudfront/distribution.json)
aws cloudfront create-distribution \
  --distribution-config "$distributionConfig" | \
  jq .Distribution.Id -r | tr -d '\n' > scripts/aws:cloudfront/distribution-id
